### ISSUE TITLE
"About" not working 

### ISSUE THREAD

**Issue by RolaSay** [graasp/graasp-desktop#134]
Using Win10. When I choose About from the menu, I don't get anything. 
I should see the info and version pop-up, but I don't.

**Comment by juancarlosfarah** [comment]
Hi @RolaSay, thanks for your feedback. Could you please provide a screenshot, if possible? @pyphilia, do you see this on your version of Windows?

**Comment by bootsa** [comment]
Same for Linux (cloned repo, master branch, 0.10.1). Click on File > About, menu closes but no pop up window or any other sign of response (no response in DevTools console either).
File menu heading stays highlighted (but that's same for other menu response: e.g. Edit > Cut) - see screenshot.
![image](https://user-images.githubusercontent.com/22413/61299365-35e19580-a7e0-11e9-8f34-380b9e232b92.png)

**Comment by RolaSay** [comment]
I normally would. But since nothing is shown when selecting File --> About, I didn't.  
![Graasp Viewer](https://user-images.githubusercontent.com/52963506/61299464-75a87d00-a7e0-11e9-8342-da43b475f401.png)

**Comment by juancarlosfarah** [comment]
I have been able to reproduce on Windows. Thanks @RolaSay for reporting.

**Comment by juancarlosfarah** [comment]
@pyphilia, could you please have a look at this? I think it's just some config that needs to be added. Prioritise Windows.

**Comment by bootsa** [comment]
Looks like Electron only has an About role for Mac (as it uses a native MacOS function).

This package (https://www.npmjs.com/package/about-window) looks like it would provide cross-platform support.

If I get the chance I'll try it out and attempt a pull request.

**Comment by juancarlosfarah** [comment]
Thanks for the comment @bootsa. @pyphilia is looking into this now. Will let you know if we resolve it.

**Comment by juancarlosfarah** [comment]
In any case, this is what we should be showing:

![image](https://user-images.githubusercontent.com/1707188/61385125-25015480-a8b2-11e9-9eb0-db376307878c.png)

**Comment by pyphilia** [comment]
I created a fix here 27b8826 
Thank you for the tip @bootsa This package works very well. 
However I experimented my electron browser getting erased. I guess it is happening during this package installation, I am not sure. We should test it.

**Comment by juancarlosfarah** [comment]
@pyphilia, it looks fine to me. Can you create a PR please?

**Comment by bootsa** [comment]
Sorry for the delay in replying. On Linux (and probably Windows) each new window has the main menu attached so it appears in the About Window. This pull request should fix it.

Out of interest, wouldn't keeping the MacOS menu system (with items like About under the application menu entry) help with navigation due to familiarity? The [example on the electron menu page](https://electronjs.org/docs/api/menu#main-process) has a good implementation - though it's missing a vital line:
```javascript
const isMac = process.platform === 'darwin';
```

**Comment by juancarlosfarah** [comment]
@bootsa, thanks for your feedback. I agree that keeping the macOS menu system would be a good idea. @pyphilia, could you kindly look into this? Thanks!

**Comment by juancarlosfarah** [comment]
@pyphilia, you can always test the Mac bit on the iMac and open a new PR if you think it works well!

**Comment by juancarlosfarah** [comment]
Hmm. I built the new version and see some difference. It looks like it's using the `graasp-desktop` name and not `Graasp`. We also seem to be missing some of the help elements in the menu.

**Previous Version**
<img width="624" alt="Screenshot 2019-07-24 at 10 42 03" src="https://user-images.githubusercontent.com/1707188/61807927-15c55e00-ae00-11e9-9765-11c466ab2c0f.png">
<img width="320" alt="Screenshot 2019-07-24 at 10 41 57" src="https://user-images.githubusercontent.com/1707188/61807928-15c55e00-ae00-11e9-9797-27c4e004350f.png">

**Current Version**
<img width="656" alt="Screenshot 2019-07-24 at 10 42 32" src="https://user-images.githubusercontent.com/1707188/61807965-237ae380-ae00-11e9-9eee-4b3c563d2556.png">
<img width="463" alt="Screenshot 2019-07-24 at 10 42 20" src="https://user-images.githubusercontent.com/1707188/61807966-24137a00-ae00-11e9-9286-ed16fb101bd7.png">

@pyphilia, perhaps open a new PR and go with @bootsa's suggestion?

**Comment by pyphilia** [comment]
@juancarlosfarah I couldn't reproduce your menu bar. I built from master and had this on the iMac 

![image](https://user-images.githubusercontent.com/11229627/61872139-dfacda80-aee2-11e9-98b8-8e323b3e7deb.png)
![image](https://user-images.githubusercontent.com/11229627/61872158-e89dac00-aee2-11e9-8e2f-00ed83c42177.png)

**Comment by juancarlosfarah** [comment]
@pyphilia, that's how it should look, but I believe you might not have the latest commit. Did you run `yarn dist` (make sure you have a copy of the `.env` file) and open the resulting `dmg` in `dist/`?

**Comment by pyphilia** [comment]
I arrange it a bit.
What I opened was the file in the `mac` folder after running `yarn dist`. I can indeed notice the difference in the menu but I am not sure why?
