### ISSUE TITLE
set up spectron

### ISSUE THREAD

**Issue by juancarlosfarah** [graasp/graasp-desktop#141]
https://electronjs.org/spectron

**Comment by pyphilia** [comment]
I am setting spectron without much problem. I however notice an issue similar to this one https://github.com/electron-userland/spectron/issues/254
`app.electron` might help me mock `dialog` for example (but I managed this with some workarounds by passing environment variables when launching the app through spectron).

As mentioned in the issue, I disabled redux tools when `NODE_ENV==='test'` but nothing changes. Maybe it comes from windows. 

Except that I can run tests more or less smoothly.

**Comment by pyphilia** [comment]
closed with #244
