### ISSUE TITLE
SpaceNotFound.js fails due to partial translation implementation

### ISSUE THREAD

**Issue by bootsa** [graasp/graasp-desktop#150]
Loading up a space from "Visit a space" (entered `5d2db762fcb4d60e33ad32fe` from `https://graasp.eu/spaces/5d2db762fcb4d60e33ad32fe`) gives an error because i18next doesn't seem to be imported and implemented fully.

![image](https://user-images.githubusercontent.com/22413/62380388-639d3d00-b549-11e9-971b-67fceec6fd40.png)

Removing t() entries from SpaceNotFound.js allows space to be loaded (previewed) as normal (obviously no translation). 

Is this normal behaviour? Shouldn't SpaceNotFound.js only be loaded when a space isn't found?

Issue seems to have been introduced in https://github.com/graasp/graasp-desktop/commit/3fbee4c0b180f03cb41473b110e016f67a7302d0#diff-4d444bdceb5a25dc656ce80cf746e9cd

**Comment by juancarlosfarah** [comment]
@bootsa you are right. There is an HOC missing here @pyphilia.

**Comment by juancarlosfarah** [comment]
@pyphilia, I'm sending a fix now. Will add you and @bootsa as reviewers so that you can have a look. @pyphilia, please merge when ready.

**Comment by juancarlosfarah** [comment]
Here is the PR @bootsa, @pyphilia.

https://github.com/graasp/graasp-desktop/pull/151
