### ISSUE TITLE
window

### ISSUE THREAD

**Issue by Fer60** [graasp/graasp-desktop#154]
When using the "Build an Atom" lab, the window in the desktop viewer fot this lab is too small to show the complete lab. You need to scroll to view the top or bottom part.
Is it possible to enlarge that window?

**Comment by juancarlosfarah** [comment]
@Fer60, thanks for your feedback. In the latest version of the viewer (0.11.3), you are able to enlarge apps and labs by holding the bottom right corner of the lab and dragging it down, as shown below.

![enlarging-labs](https://user-images.githubusercontent.com/1707188/62539232-052bd380-b855-11e9-9097-06a76dc5a37d.gif)

**Comment by Fer60** [comment]
Hi Juan Carlos,

It works, thanks.

Cheers,

Fer



dr. Fer Coenders,
GO-GA, Department of Instructional Technology (IST)
Faculty BMS, University of Twente
https://www.golabz.eu<https://www.golabz.eu/>
https://www.utwente.nl/en/bms/ist/
Tel (+31) 053-4893081 )office); (+31) 0316-228920 (home)

**Comment by juancarlosfarah** [comment]
Awesome! Thanks again for testing it out.
