### ISSUE TITLE
version 0.11.4 is showing white screen

### ISSUE THREAD

**Issue by juancarlosfarah** [graasp/graasp-desktop#156]
Although the runtime Electron version of v0.11.4 works fine, the build binary is showing a white screen on mac.

**Comment by juancarlosfarah** [comment]
Change introduced in commit: https://github.com/graasp/graasp-desktop/commit/787b19e07bda7040df5bc1795c8a0cf3faee7d5a

**Comment by juancarlosfarah** [comment]
Issue is that we cannot change the `homepage` in the package.json, as create-react-app uses it to build the frontend. Fixing by defining the homepage in the `openAboutWindow` function instead.

**Comment by juancarlosfarah** [comment]
Tagging @bootsa for awareness.

**Comment by juancarlosfarah** [comment]
@bootsa, @pyphilia, please check that everything is working in Windows as expected.

**Comment by bootsa** [comment]
That's a bit of an annoyance, CRA.

Confirm `graasp-desktop-0.11.5-x86_64.AppImage` appears to work fine. Haven't got `graasp-desktop_0.11.5_amd64.snap` working because of #143.
