### ISSUE TITLE
size / white lines

### ISSUE THREAD

**Issue by Fer60** [graasp/graasp-desktop#163]
In the desktop viewer the white lines have disappeared.
In the investigation phase of the offline version (Atomic structure) I have used (from top to bottom): a document (text), a PhET lab (that misses the scroll arrow at the bottom), a Table (Tabel tool 2) and a document with text.
The Table is positioned straight at the lab (there are no white lines) and the text of the document under the Table is only partly visible. At the right hand side of the Table a part of a scoll bar is visible. With this the text of the last document can be moved down. 
But it would be nice when it could look like the online version.

**Comment by jakob-sikken** [comment]
When the table tool is loaded, it gets the initial height. Then the configured nr rows/columns (and content) is set, which causes the height to increase. Then the height of the iframe is adjusted to the used height. As the text element below the the table tool iframe is not moved down, the table tool iframe is hiding part of the text element.
Changes of the app iframe height should move all elements below the app.

**Comment by juancarlosfarah** [comment]
@jakob-sikken, I'm not sure if I'm doing anything wrong, but the app does not seem to work offline.

![image](https://user-images.githubusercontent.com/1707188/62967260-e905d480-be08-11e9-92fe-292fddb67898.png)

@Fer60, you are still using the space with short ID `7slvq0`, right?

**Comment by jakob-sikken** [comment]
Fer complained about a similar problem, but after a refresh of the ils in the graasp desktop app, the problem was solved. I am not the owner of that ils, so I can't test anything.

**Comment by Fer60** [comment]
Yes, 7slvq0 is the short link.

Cheers,

Fer



dr. Fer Coenders,
GO-GA, Department of Instructional Technology (IST)
Faculty BMS, University of Twente
https://www.golabz.eu<https://www.golabz.eu/>
https://www.utwente.nl/en/bms/ist/
Tel (+31) 053-4893081 )office); (+31) 0316-228920 (home)

**Comment by juancarlosfarah** [comment]
This has been fixed in [v0.12.0](https://github.com/graasp/graasp-desktop/releases/tag/v0.12.0). Problems with table tool not working in preview mode are being tracked in #171.
